title: Ved Pratap
logo: /assets/logo.jpg
email: vpratap8340400@gmail.com
description: SDE @ Open. Python Developer. Machine Learning.
favicon: false
remote_theme: vedpratap/jekyll-theme-minimalistic
color-scheme: light

google_analytics: G-0RXV630V8X

url: "https://vedpratap.me/"

plugins:
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme
  - jekyll-sitemap

platforms:
  - name: Résumé
    icon: <i class="fa-solid fa-file-lines"></i>
    link: ./assets/files/ved_pratap_resume.pdf
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/vedpratap
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/vedpratap
  - name: Projects <span class="badge text-bg-success">5</span>
    icon: <i class="fa-solid fa-file-code"></i>
    link: ./projects
  - name: Certifications <span class="badge text-bg-success">5</span>
    icon: <i class="fa-solid fa-award"></i>
    link: ./certifications
  - name: LeetCode
    icon: <i class="fa-solid fa-laptop-code"></i>
    link: https://leetcode.com/vedpratap/
  - name: CodeChef
    icon: <i class="fa-solid fa-laptop-code"></i>
    link: https://www.codechef.com/users/vedpratap
  - name: HackerRank
    icon: <i class="fa-solid fa-laptop-code"></i>
    link: https://www.hackerrank.com/21f1000886
  - name: Open Source
    icon: <i class="fa-solid fa-ghost"></i>
    link: ./open-source
